### ISSUE TITLE
Render curved quotes

### ISSUE THREAD

**Issue by xcoulon** [bytesparadise/libasciidoc#176]
See https://asciidoctor.org/docs/user-manual/#curved

**Comment by shuLhan** [comment]
@xcoulon Can you give an example for this case?  I have an issues that may or may not related to single/double quotes, to minimize duplicate issue which I want to report.

Thank you.

**Comment by xcoulon** [comment]
@shuLhan my case is that for text such as `mother's day` will be output as `mother&#8217;s day`. 

See https://asciidoctor.org/docs/user-manual/#curved. I'll edit the issue title and description to clarify.

**Comment by xcoulon** [comment]
@shuLhan don't hesitate to open a new issue if you found a bug ;)

**Comment by gdamore** [comment]
So it turns out that I need this too (I used this syntax extensively in my docs).

There are two dimensions of this problem.

First, we need to support "` and `"  (and also '` and `') elements.  These are inline elements like a String Element.  Notably asciidoctor does not process these "sanely" if they cross a paragraph (and presumably any block) boundary.  This probably creates some challenges to their use.  Which is unfortunate, because nobody really wants to type "&8217;."

Secondly, is the problem of automatically recognizing that a lone apostrophe should be curved when it appears without whitespace, along with the code to be smart about the use of "\" to escape them.

The particular rules also need to be savvy about `code` blocks, which creates some real challenges.  TBH, I believe that there can be ambiguity in the mark up language.

I'm not entirely sure how best to solve this.  The need is pressing for me, because I did use it heavily.  I might just "fix" my documents to use replacements instead.

I've got a solution which I think mostly does the right thing for apostrophes like mother's day, but a general solution to the explicit typographic entities is likely to be harder.

**Comment by gdamore** [comment]
Actually in this day and age, we have unicode.  I know this is mean to be "ASCIIDOC", but really, there is no reason we can't inject UTF-8 explicit characters into place.  That's what I would recommend folks do for now.

**Comment by gdamore** [comment]
See also #620.  I am considering *this* bug to just be the handling of mother's day style markup, with a renderer time substitution (for now -- although we might want to do this at parse time in the future).

**Comment by gdamore** [comment]
So there are two cases to cover here.

1. mother's day (apostrophe with letters on both sides)
2. mothers`' day  (typographic curved apostrophe)

It would be most natural to render these typographically using unicode on the backend, and then replace the unicode with an escaper for the asciidoctor compatible HTML.  (Other backends should not use those escapes, and frankly are better off *not* doing so -- even in asciidoctor the epub backend leaves unicode unmolested.)
