### ISSUE TITLE
man page doc type not honored

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#511]
It seems that sending doctype: manpage doesn't do anything.  In asciidoctor it slightly changes the output in the title.  This isn't a big deal for me, but the difference was something I noticed.

**Comment by xcoulon** [comment]
note: see https://asciidoctor.org/docs/user-manual/#man-pages for manpage requirements

**Comment by gdamore** [comment]
I'd rather not wait for this change -- it's not crucial to me, so if it were a v0.4.0, and I could get v0.3.1 sooner, that would make me happy.

**Comment by xcoulon** [comment]
> I'd rather not wait for this change -- it's not crucial to me, so if it were a v0.4.0, and I could get v0.3.1 sooner, that would make me happy.

@gdamore I'd like to have this issue fixed for this release since all the work I did on https://github.com/bytesparadise/libasciidoc/issues/517 was to fix another issue I discovered while working on this one. 

Also, if I may suggest: it is a bit tricky to "compute" the timestamp + commit hash for the latest version of a module, but in your case here you can run 
```
go get -u github.com/bytesparadise/libasciidoc@master
``` 
and it will download and update your project's `go.mod` with `github.com/bytesparadise/libasciidoc v0.3.1-0.20200329145152-c0f5b5c06d12` (at the time of writing this message)

**Comment by xcoulon** [comment]
@gdamore it should be fixed now ;) Please let me know if it works for you.

**Comment by gdamore** [comment]
I will look tomorrow.  I’ve been a bit distracted lately.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
