### ISSUE TITLE
Support multiple roles on all blocks

### ISSUE THREAD

**Issue by xcoulon** [bytesparadise/libasciidoc#602]
A paragraph or a delimited block may have multiple roles (which should be retained in a slice).

Eg:
````
[.role1]
[.role2]
a paragraph
````

**Comment by gdamore** [comment]
I'm working on this as part of a general refactoring of the templates.

**Comment by gdamore** [comment]
This shouldn't have closed that way.... I guess the PR comments (not the merge comments) cause the closure.  Reopening, as it's not fixed still.

**Comment by gdamore** [comment]
I've made some progress on this -- the attributes parser is much more robust now.  However, I still need to implement the various paragraph types, and I need to write tests.  The latter is the most time consuming (and tedious) part of this project.

**Comment by xcoulon** [comment]
> I've made some progress on this -- the attributes parser is much more robust now. However, I still need to implement the various paragraph types, and I need to write tests. The latter is the most time consuming (and tedious) part of this project.

yes, I know... but it's a guarantee of quality ;)

**Comment by xcoulon** [comment]
@gdamore do you have some work in progress that I could take over to address this issue? Or shall I start from scratch?

**Comment by xcoulon** [comment]
@gdamore I will probably take a look at it since I haven't seen any response from you here, unless you want to submit a PR?

**Comment by gdamore** [comment]
That’s fine.

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by gdamore** [comment]
To be clear I've always felt this was something that was being done incrementally.  Most of the work is already done and integrated.  It's been a while since I looked more closely to determine which blocks are still in need of work... you were changing a bunch of stuff, so I set aside that work.

I'm happy for you to finish it up. :-)

I'd like to resume the work to make an epub backend soon, I may need to mostly start over because so much has changed since I started.
