### ISSUE TITLE
Section ID should include the icon class

### ISSUE THREAD

**Issue by xcoulon** [bytesparadise/libasciidoc#691]
For example:
```
== icon:warning[] or what icon:note[] to do
```
should render as 
```
<div class="sect1">
<h2 id="_warning_or_what_note_to_do"><span class="icon">[warning]</span> or what <span class="icon">[note]</span> to do</h2>
<div class="sectionbody">

</div>
</div>
```

(note the `id="_warning_or_what_note_to_do"` in the `<h2>` element)

**Comment by xcoulon** [comment]
(to hold until #633 is done)

**Comment by gdamore** [comment]
I actually think that we should probably create an interface, for stuff like this, so that renderElementID can look at the elements, and get the "elementID" portion from that element, and concatenate them together.

Right now our forest of element types has no common API, which is probably somewhat unfortunate.

I'm also thinking that instead of creating local custom types in the render at the call site, we could actually have local types that implement a "Render" method.  E.g.

```
// in the SGML or HTML packages...

type Table = types.Table

func (t Table) Render() (string, error) { .... }
```

Attribute substitution and expansion (intermediate parsing) might also be handled in a similar way.

This probably deserves a bit (ok a lot) more thought.

**Comment by gdamore** [comment]
Actually what about images -- should they pick up the alt text?

And what about if the icon has an alternate text (alt) applied?
