### ISSUE TITLE
Closing html tag should have a newline appended

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#702]
Asciidoctor does not do this, but I think it's a mistake.

I believe the closing HTML tag should have a newline appended.  Most editors consider it to be a warning situation when the last line in a file does not end with a newline.

Technically, HTML doesn't care.  But this is one small think that I think we could do to make it better for anyone who works with the output from libasciidoc.

**Comment by xcoulon** [comment]
wasn't it solved in https://github.com/bytesparadise/libasciidoc/pull/701?
I can see a newline in https://github.com/bytesparadise/libasciidoc/pull/701/files#diff-0b1970b411fe5e4726e0e275786234ed for example

**Comment by gdamore** [comment]
I didn't add them on `</html>` tags.  For all the other closers I did.  I wanted to minimize the changes to extant docs -- adding this change makes *every* document (full document) result in different output (a finishing newline) -- so I felt it best to leave this as a separate issue.

**Comment by xcoulon** [comment]
ok, but I'm still confused by this change, though: https://github.com/bytesparadise/libasciidoc/pull/701/files#diff-0b1970b411fe5e4726e0e275786234ed
or maybe you intend to have an extra line return after the closing `</html>`?

**Comment by gdamore** [comment]
I can't tell (link isn't working well for me) which part of the diff you are referring to.

**Comment by xcoulon** [comment]
> I can't tell (link isn't working well for me) which part of the diff you are referring to.
yeah, sometimes links don't work because it refers to a file which is not "expanded" in the review page (because the change is too big). I understand that GitHub wants to avoid displaying all the changes at once, but that's a bit annoying because link sharing doesn't work :( 


I'm referring to the last line of https://github.com/gdamore/libasciidoc/blob/f209dc8290b65ed5834931d2c7e4c6b6f4205f00/test/fixtures/supported/article.html
In the commit diff, we can see a change after `</html>` so I was wondering if it was the kind of change you intended to provide in this issue?

**Comment by gdamore** [comment]
That file doesn't end with a `</html>` tag.

**Comment by xcoulon** [comment]
🤦‍♂️

**Comment by xcoulon** [comment]
my apologies, I misread 😬
